FLETES_SIIGO = {
    "JUAN CARLOS ROJAS": {
        "Nombre": "JUAN CARLOS ROJAS AGREDO",
        "identification": "1083874987",
        "nit": "1.083.874.987-7",
        "direccion": "CLL3 C SUR 5 5-17 E",
        "telefono": "3208566116",
        "ciudad": "Pitalito - Colombia",
    },
    "ESNEDA HERNANDEZ": {
        "Nombre": "ESNEDA HERNANDEZ ROSERO",
        "identification": "30509423",
        "nit": "30.509.423-8",
        "direccion": "	BARRIO LOS NOGALES",
        "telefono": " 3208566116",
        "ciudad": "Pitalito - Colombia",
    },
    "BRAYAN ROLDAN GARCIA": {
        "identification": "	1007404632",
        "nit": "1.007.404.632-6",
        "direccion": "BRR CALLE 10 N 5-44",
        "telefono": "3208566116",
        "ciudad": "Gigante - Colombia",
    },
}

PROVEEDORES = {
    "LAURA GABRIELA OSORIO VALDERRAMA": "GABRIELA VALDERRAMA",
    "OSCAR DANIEL LOMBANA LOPEZ": "BARFIT",
    "AGROSOLLA SAS": "AGROSOLLA SAS",
    "COLOMBOSALES": "COLOMBOSALES SAS",
    "LABORATORIOS LAVERLA": "LABORATORIOS LAVERLAM SA",
    "DISPROVET COLOMBIA SAS": "DISPROVET COLOMBIA SAS",
    "ENERVIDA SAS": "ENERVIDA SAS",
    "TELEVIGILANCIA LTDA": "TELEVIGILANCIA LTDA",
    "OLVER ANTURY CARVAJAL": "OLVER ANTURY CARVAJAL",
    "PROANDINA": "SIERRA PINEDA",
    "LA CASA DEL GANADERO": "LA CASA DEL GANADERO",
    "CENTRAL PECUARIA SA": "CENTRAL PECUARIA S.A.",
    "LAB EDO SAS": "LABORATORIOS EDO SAS",
    "ALIMENTOS POLAR SAS": "ALIMENTOS POLAR",
    "GABRICA SAS": "GABRICA SAS",
    "INVERCIONES AGROCOSUR": "INVERSIONES AGROCOSUR",
    "TAMAYO POLANCO SAS": "TAMAYO POLANCO",
}

FLETES = {
    "ESNEDA H": "ESNEDA HERNANDEZ",
    "BRAYAN GARCIA": "BRAYAN ROLDAN GARCIA",
    "JUAN CARLOS": "JUAN CARLOS ROJAS",
}

NOMINA = {
    "ANDRES CORTEZ": "ANDRES CORTEZ",
    "JULIAN LOPEZ": "JULIAN LOPEZ",
    "EDUARDO SANCHEZ": "EDUARDO SANCHEZ",
    "LUISA LOPEZ": "LUISA MARIA",
    "CARLOS OLAYA": "CARLOS OLAYA",
    "JUAN CAMILO CASTILLO": "CAMILO CASTILLO",
    "ANDRES FELIPE CLAROS": "ANDRES CLAROS",
    "JOHN FREDDY MAPALLO GAVIRIA": "JHON MAPAYO",
    "KAREN YURLEI MAPALLO BOLA": "KAREN MAPAYO",
    "HEINERT ZU": "HEINERT ZUÑIGA",
    "EDGAR ANDRES POLANCO": "EDGAR POLANCO",
    "DUVAN ANDRES GUZMAN CRUZ": "DUVAN ANDRES",
    "WILMER NICOLAS BRAVO": "NICOLAS BRAVO",
    "BRAYHAN RODRIGUEZ": "STIVEN RODRIGUEZ",
}
